# H2
h2:
  console:
    enabled: true
    path: /h2

# Datasource
spring:
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

# Logging
logging:
  level:
    org.springframework.web: DEBUG